# erp_client.py
import httpx, os

BASE = os.getenv("PHOENIX_API_BASE_URL")
TOKEN = os.getenv("PHOENIX_API_TOKEN")
HEADERS = {"Authorization": f"Bearer {TOKEN}"}

async def list_tickets(): ...
async def get_customer_system(ticket_id): ...
async def create_activity(payload): ...
async def patch_ticket_status(ticket_id, status): ...